"""
PosVec: Position vectors for Go board
represents coordinates as (i, j) array indices:
    (i, j) <--> board[i][j]

"""

class PosVec:

    # static variable representing size of board
    SIZE = None

    def __init__(self, i, j):
        self.i = i
        self.j = j

    # objects treated as equal iff they have the same coordinates
    # handles duplicate PosVecs (re-generated by getLegalMoves)
    # def __eq__(self, other):
    #     result = [self.i == other.i] and [self.j == other.j]
    #     return result

    # overrides conversion to string
    def __str__(self):
        result = "sq ({i}, {j})".format(i = self.i, j = self.j)
        return result

    # bool describing whether the vector is on the go board
    def inRange(self):
        coordRange = range(PosVec.SIZE)
        result = (self.i in coordRange) and (self.j in coordRange)
        return result

    # returns new vec representing this vec, but displaced
    def add(self, disp):

        new_vec = PosVec(self.i + disp.i, self.j + disp.j)
        return new_vec

    # finds board value at given position
    def indexInto(self, board):

        if self.inRange():
            node = board[self.i][self.j]
            return node
        # if coords not in range, return None
        else:
            return None
